# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pidctl.gjx.me/"

git_url = "https://github.com/JunxinGao/pidctl/tree/master/"

def custom_doc_links(name): return None
