# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['kwargs2str']

# Cell
from .imports import *

# Cell
def kwargs2str(**kwargs):
    str_list = [f"{k}: {v}" for k, v in kwargs.items()]
    return ", ".join(str_list)